### ISSUE TITLE
Error I received when I was on the tab watchdog of the remote (clicked on opc)

### ISSUE THREAD

**Issue by stephanieder** [partnering/neuron-base#1]
Uncaught TypeError: Cannot read property 'writeAll' of nullDiyaBehaviors.Neuron.sendAll @ neuron-base.html:59(anonymous function) @ neuron-base.html:51
diya-sdk.min.js:2 Open datachannel pa.contexts

**Comment by antoineDeRengerve** [comment]
![image](https://user-images.githubusercontent.com/10978052/48060211-a2b98000-e1bb-11e8-90de-8ce57d256e77.png)

Same error
